### ISSUE TITLE
Does not calculate for long stays?

### ISSUE THREAD

**Issue by mark05e** [davidsawyer/airbnb-price-per-night-correcter#12]
Thank you for creating this extension. I found a minor issue when I try to check dates for 2 months or so - it does not show the extension calculated price.

When i check for dates under a month it seems to be fine.

I have tried to demo it in this video:
[![youtube demo of the issue](https://img.youtube.com/vi/iFmkwzUnWpg/0.jpg)](https://www.youtube.com/watch?v=iFmkwzUnWpg)

**Comment by mark05e** [comment]
Sorry I just read the todo list 😬

-   [ ] _handle monthly price_

**Comment by davidsawyer** [comment]
Haha no worries!
