### ISSUE TITLE
Add on for Android?

### ISSUE THREAD

**Issue by wonkalonk** [davidsawyer/airbnb-price-per-night-correcter#3]
I installed the AIR B N B PRICE PER NIGHT CORRECTOR Add on for Chrome Windows. It works well.  May I please know, will this also work for Android? Thank you.

**Comment by davidsawyer** [comment]
Hey, I don't know much about Android add-ons and therefore don't currently have any plans to work on  one for this project. Though, I'd welcome a pull request for that if it was relatively small in scope!
