### ISSUE TITLE
Price per month

### ISSUE THREAD

**Issue by CryptoD** [davidsawyer/airbnb-price-per-night-correcter#4]
The addon shows price per day or week fine but doesn't correct prices when I want to rent for a month

![deepinscreenshot_20180616125938](https://user-images.githubusercontent.com/25362387/41498113-543c2da4-7165-11e8-943a-b52cd7594e1c.png)

**Comment by davidsawyer** [comment]
We already have this as a todo list item [here](https://github.com/davidsawyer/airbnb-price-per-night-correcter#todos). Pull requests welcome!
