### ISSUE TITLE
Price discrepancy by factor of ten on price per night 

### ISSUE THREAD

**Issue by laura-callahan** [davidsawyer/airbnb-price-per-night-correcter#5]
Found an airbnb that should be $491.19 per night incl fees, but is showing as $49,119 instead.
<img width="410" alt="screen shot 2018-08-28 at 13 24 51" src="https://user-images.githubusercontent.com/9971478/44746413-89170080-aac7-11e8-8617-d026e0da0175.png">

**Comment by davidsawyer** [comment]
Thanks for the report!

Looks like Airbnb recently started including cents in their Total price for the entire trip, and that's what caused the parsing error. [This commit](https://github.com/davidsawyer/airbnb-price-per-night-correcter/commit/b77a2a969911f5d62aaccf7c3b3ea7003ac28fe4) should fix the problem. The latest version (0.4.1) has been pushed to the Chrome and Firefox stores as of about 10 minutes ago and should be available to all users within about an hour.
