### ISSUE TITLE
Correct prices on the search page

### ISSUE THREAD

**Issue by aaomidi** [davidsawyer/airbnb-price-per-night-correcter#6]
Is there a way to display this on the search rather than on click?

**Comment by davidsawyer** [comment]
This is by far the most popular feature request. I’d happily accept a PR that accomplishes this, but I’m just concerned with the potential complexity involved. This extension is super simple at the moment, so I’ll definitely need to carefully consider any big new features that might be added.

**Comment by bbodenmiller** [comment]
Would like to see this also.

**Comment by Stvad** [comment]
Right now the Airbnb displays "total" alongside the item which includes *almost* all fees (seems like govt fees are not included, but those seem to be stable/ish)

I have the following snippet to sort the listings by total. You can probably infer proper price based on the total as-well

```js
allOnScreen1 = document.querySelectorAll("._8ssblpx")

allOnScreen1 = 
homes1 = [...allOnScreen1].map(el => {

    const url = el.querySelector('meta[itemprop="url"]').content

    const totalText = el.querySelector('._1asxs4e > ._krjbj').innerText
    return {
        name: el.querySelector('meta[itemprop="name"]').content,
        link: url,
        totalPrice: totalText.match(/\d+/)[0],
        original: el,
    }
})

homes1.sort((a, b) => a.totalPrice.localeCompare(b.totalPrice))

parent = document.querySelector("._fhph4u")
parent.replaceChildren(...homes1.map(it=>it.original))
```

**Comment by davidsawyer** [comment]
Hey, nice work! And yeah, I hate how the exclude the government taxes and fees on that total. They were so close!!

I think I'll only be willing to add this sort of thing to the extension once we have a more bulletproof solution. I wonder if there's a private API endpoint where we could discover the government fee/tax formula 🤔
