### ISSUE TITLE
Plugin not changing any text (November 2019)

### ISSUE THREAD

**Issue by Bryan-Tam** [davidsawyer/airbnb-price-per-night-correcter#9]
As the issue states, the plugin is not working as intended and none of the text in the listing is changing (see image).
![image](https://user-images.githubusercontent.com/6621149/68359228-3b455180-00e9-11ea-90f1-65895306a7ce.png)

**Comment by davidsawyer** [comment]
Hey @Bryan-Tam, you're in luck! I just updated the extension to fix this issue (and many others). It should be available in both Chrome and Firefox right now, if not very soon!
